### ISSUE TITLE
Rasberry pi 4 not conecting to head unit

### ISSUE THREAD

**Issue by bahmad6890** [nisargjhaveri/WirelessAndroidAutoDongle#101]
I am trying to compare the performance between Raspberry Pi Zero and Raspberry Pi 4. I created an SD card with the pre-built image provided here. The Raspberry Pi Zero works perfectly, while my phone connects to the Raspberry Pi 4 and I can see my Wi-Fi is connected to the Raspberry Pi but not to my head unit, whereas the Raspberry Pi Zero is working fine. For the Raspberry Pi 4, I used a USB Type-A to Type-A cable and a separate 5-volt power supply. Could you advise on troubleshooting this issue?

**Comment by posh6876** [comment]
I am also using rpi 4 and it is working fine.  However, i used the usb c not the usb a of rpi 4.  The version 4.0 works perfectly for my subaru ascent.

> I am trying to compare the performance between Raspberry Pi Zero and Raspberry Pi 4. I created an SD card with the pre-built image provided here. The Raspberry Pi Zero works perfectly, while my phone connects to the Raspberry Pi 4 and I can see my Wi-Fi is connected to the Raspberry Pi but not to my head unit, whereas the Raspberry Pi Zero is working fine. For the Raspberry Pi 4, I used a USB Type-A to Type-A cable and a separate 5-volt power supply. Could you advise on troubleshooting this issue?

**Comment by bahmad6890** [comment]
Thank you very much working fine now. with USB C
