### ISSUE TITLE
Does the Pi Board matter? 

### ISSUE THREAD

**Issue by prashantchoudhary** [nisargjhaveri/WirelessAndroidAutoDongle#115]
Does it matter which Raspberry I use. Is there a minimum RAM, processor speed requirement? I believe 5Ghz would be more stable for wifi, but confused on RAM and Processor department. PLease help

**Comment by nisargjhaveri** [comment]
So far, I've not seen any significant difference across RPi Zero 2W and RPi 4, apart from boot speed. The CPU and RAM utilisation is generally low. The 5Ghz wifi can sometimes help with interference depending on your situation.

**Comment by prashantchoudhary** [comment]
Thank you for your response, will start experimenting then. (probably Zero due to the form factor)
