### ISSUE TITLE
Connection Issue: 2016 F150 running Sync v3.4 - RP zero 2 W

### ISSUE THREAD

**Issue by jeffhoagland** [nisargjhaveri/WirelessAndroidAutoDongle#117]
I believe I'm running Sync 3.4 - I checked it awhile ago, and I believe this is right but I'm not in my truck at the moment to check it again.

Like @KonradSC, in Issue #116 - I'm having a connection issue.  In my case, my ZFold5 appears to find the RPi 0 2W as both a WiFi and a BT endpoint, however, when it comes to connecting to BT for the connection to the HeadUnit to start, it seems to "stall" after recognizing  the BT (AndroidAuto-Dongle) and adding it to the "Paired Devices" list, where it shows the option to "Connect" to this BT endpoint, however it never does.

Here are my logs:
[Android auto log 2 20240504.docx](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/files/15366061/Android.auto.log.2.20240504.docx)
[Android Auto log 20240504.docx](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/files/15366062/Android.Auto.log.20240504.docx)

I also looked at these files hoping to find something useful, however I wasn't able to make any sense of what is in there, but I didn't see anything that meant anything to me in either one save for my BT MAC address (I found "dev_18_26_54_1C_CC_1E" in nearly every file)
[dnsmasq.leases-20240504.docx](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/files/15366070/dnsmasq.leases-20240504.docx)
[hostapd-20240504.docx](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/files/15366071/hostapd-20240504.docx)

HTH - let me know if I can provide any additional details to help resolve this issue

**Comment by nisargjhaveri** [comment]
Does your phone show connected to the head unit's bluetooth as well when your try to connect to the dongle? You need to first start AA with wire and then when trying to connect wirelessly, you need to make sure that the car's bluetooth gets connected to the phone. Just making sure this requirement was met.

**Comment by jeffhoagland** [comment]
Maybe I misunderstood - I thought the phone connected via BT to the rPi,
via AndroidAuto-Dongle.

I believe it was connected to the "Sync" BT connection at the point where
the setup process stalls/breaks.

I will attempt again, and report back

**Comment by jeffhoagland** [comment]
It appears that I fell victim to my USB cable.  I tried a brand new cable and was able to get it to work.  Also, with doing that I also believe that deleting my previous Android Auto connection, then redefining the new connection specifically for this process was what really solved my issue.

At this time I am able to establish connection using the rPi0 2W without any further issues (at least once, haven't tested if it will maintain through restarting the vehicle)

**Comment by NoGare** [comment]
@jeffhoagland Can this ticket be marked as closed then?

**Comment by jeffhoagland** [comment]
Yes, I have everything working now

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
