### ISSUE TITLE
OpenCarOS NG

### ISSUE THREAD

**Issue by gordonpow** [nisargjhaveri/WirelessAndroidAutoDongle#121]
Can I use Bluetooth connection with Crankshaft OpenCarOS NG v2022.09.12.1? If so, please tell me how to turn it into an IMG file.

**Comment by nisargjhaveri** [comment]
I'm really not an expert, but Crankshaft should already support wireless android auto natively, no? In any case, can you please elaborate on what you're trying to do? If the question is about Crankshaft, I'd suggest asking on their repository?
