### ISSUE TITLE
Would the invese be possible

### ISSUE THREAD

**Issue by sylvaindc** [nisargjhaveri/WirelessAndroidAutoDongle#127]
Here is a crazy idea, would the invese be possible? As in, using a USB (OTG?) cable to connect your phone to a PI and let the pi connect to a wireless Android Auto headunit. That would allow easy switching between phones when only a wireless connection is possible

**Comment by nisargjhaveri** [comment]
I haven't given this much of a thought, but from top-of-mind, sure, it should be possible. We'll have to implement both host usb on the Rpi and the client side of the Wireless AA connection.

> That would allow easy switching between phones when only a wireless connection is possible

Wouldn't you be able to just connect phone with wire to the headunit directly?
