### ISSUE TITLE
Change bluetooth name

### ISSUE THREAD

**Issue by krish-ag** [nisargjhaveri/WirelessAndroidAutoDongle#128]
I want to change the bluetooth name of raspberry pi from AA wireless Dongle (or Android-Auto Dongle) to something of my own.. could you tell me if there's an environment variable of the places i need to change the name in the source before rebuilding?

**Comment by Grafton1046** [comment]
Interested in this as well, so i can run 1 in each car and not have my phone fight's with my wife's depending on who's car we're in.
