### ISSUE TITLE
Does pre-built image has the operating system?

### ISSUE THREAD

**Issue by MrABC11** [nisargjhaveri/WirelessAndroidAutoDongle#130]
Hi! As a beginner, I want to ask a question about pre-built image. Do I need to install an operating system beforehand or the "pre-built" image has it already?

I am planning to write the pre-built image directly via Raspberry Pi Imager.

**Comment by nisargjhaveri** [comment]
Pre-built images standalone sd card image that you can directly write using the Raspberry Pi Imager.
