### ISSUE TITLE
Is it possible to flash on PICO-i.MX7D board from Android Things?

### ISSUE THREAD

**Issue by SaqibJDev** [nisargjhaveri/WirelessAndroidAutoDongle#132]
Hi,

I have an Android Things kit lying around which is PICO-i.MX7D board. Since Google killed the project, I was hunting for an idea to make some use of it, and looking at this opportunity makes perfect sense :D 

What would I need to change to run on that board? I'm hopeful I could get some Linux version on that board. Or is the image with some additional config enough?

**Comment by nisargjhaveri** [comment]
You can check if the upstream buildroot supports this board. If it has support for it, you might be able to setup and build for it.

**Comment by nisargjhaveri** [comment]
I don't have the board to test. Do let us know if you ever get it working.
