### ISSUE TITLE
Images are corrupt?

### ISSUE THREAD

**Issue by arrees** [nisargjhaveri/WirelessAndroidAutoDongle#142]
Hi, When downloading PI 3A the image and then trying to write it, I get errors. I've downloaded it multiple time with the same issue.
 
![image](https://github.com/user-attachments/assets/6f244885-8d75-494e-8f65-f31e426a44c5)
I've tried Etcher, Rufus etc. Using Zzip for Extracting the img shows an corruption error too.

Cheers,
Andy

**Comment by CsabaLevente** [comment]
same here with raspberrypi0w-sdcard.img.xz

**Comment by superbillen** [comment]
You have to extract the file with 7-zip its still compress as the Xz extension are ind the end.
When its extracted and only.img you can flash this

**Comment by nisargjhaveri** [comment]
Looks like an issue with Balena Etcher. See https://github.com/balena-io/etcher/issues/4064, https://github.com/balena-io/etcher/issues/4258. Seems like after uncompressing, it might work.

You can also use alternate softwares such as [Raspberry Pi Imager](https://www.raspberrypi.com/software/) also in the meantime.

**Comment by arrees** [comment]
Yes, you're correct. Raspberry Pi manager works! THank you.

Should the pi3A+ image work with a pi3B+?

**Comment by nisargjhaveri** [comment]
RPi 3 B+ is not supported. See #140
