### ISSUE TITLE
2020 Chevy Silverado doesn't find AA Wireless devices 

### ISSUE THREAD

**Issue by moose09876** [nisargjhaveri/WirelessAndroidAutoDongle#143]
Vehicle is a 2020 Silverado. Wired AA works great. Multiple dongles will not show up as AA Devices. Stumbled here to try and get some logs / troubleshooting. My phone will connect to the AA Wireless but the head unit keeps saying searching for phone. Using a Pi Zero W operates the same way they all do. I was able to pull the messages log, it's attached. Any help would be spectacular, as I know there are many others that are in this boat as well. Also added log from same Pi and phone, but on a VW that works fine.

[2020Silverado.txt - Broken](https://github.com/user-attachments/files/16717362/2020Silverado.txt)
[2011VW.txt - Working](https://github.com/user-attachments/files/16718546/2011VW.txt)

**Comment by nisargjhaveri** [comment]
The logs does not seem to clearly point to a an issue. Both USB and Wifi connection seem to be started correctly. A quick search seems to suggest more people might be having similar issues with other adapters as well, and unpairing and clearing cache of both headunit and phone seems to help sometimes. I can't confirm though, but maybe worth a try?

**Comment by moose09876** [comment]
I've had 3 different phones since I've started trying this. The phone side works fine. The truck does not see any of the AA Wireless device as Android Auto compatible, including the Pi.

**Comment by moose09876** [comment]
Trying to find out how to get some more logging to see what the difference is between the phone and the wireless adapter, but not finding much.

![Screenshot_20240826-094726](https://github.com/user-attachments/assets/f7450e61-9fb4-4deb-bb1a-b537c9583f64)
![Screenshot_20240826-094103](https://github.com/user-attachments/assets/c4160f91-68ed-4d61-83e0-3c60ea3ce9fc)
![PXL_20240826_134738389](https://github.com/user-attachments/assets/b79d274c-8285-4406-bcd1-e469977570c7)

**Comment by moose09876** [comment]
Thanks to Motorola support for giving me some steps that resolved this:

- remove the AAWireless device from the phone's Bluetooth devices
- remove the head unit from the phone's bluetooth devices
- remove the phone from the head unit's list of Bluetooth devices
- reset the AAWireless device (other devices, press and hold the button on it for about 45 seconds; during that time it should change color several times
- unplug the AAWireless device
- connect AAWireless device to vehicle USB
- pair AAWireless device with phone in the phone's bluetooth settings
- wait for 30 seconds while phone connects
- after the Map screen/Android Auto should pop up
- phone should prompt for bluetooth access to vehicle

**Comment by nisargjhaveri** [comment]
Glad that you were able to make it work. Thanks for sharing the steps as well.
