### ISSUE TITLE
Chevy Tahoe 2018, pi 0 works

### ISSUE THREAD

**Issue by mylife4aiurr** [nisargjhaveri/WirelessAndroidAutoDongle#148]
Read an article on beebom showing how to make a wireless android auto dongle with a pi. I had a spare pi 0 laying around, downloaded your image and followed the directions. Had a connection issue at first but got it working. This saved me from having to buy a wireless dongle from amazon. Donated to the project.

Seems to work fine on chevy tahoe 2018 head unit with a pi 0. Still need to test more but so far so good.
(not an issue, just saying it works)

**Comment by nisargjhaveri** [comment]
Glad that this project helped! And thanks a lot for the sponsorship, it helps!
