### ISSUE TITLE
ALTO K10 2023 OEM HEAD UNIT WORKING 

### ISSUE THREAD

**Issue by Mubarak3786** [nisargjhaveri/WirelessAndroidAutoDongle#149]
I just try, first I don't believe but finally it working on first attempt google map working find but some time audio laging on playing music via bluetooth.

**Comment by nisargjhaveri** [comment]
Glad that it worked for you. :)

The slight music lag is tracked in other issues. We don't have a nice solution though. My current hunch is Wifi interference, so a 5 GHz Wifi might help if your board supports it. But I have not been able to confirm this yet

**Comment by Mubarak3786** [comment]
All work nice but some time map freeze but music play normally, how to solve this problem
