### ISSUE TITLE
Able to connect to Android Auto on my Tata Nexon, however unable to use mobile internet.

### ISSUE THREAD

**Issue by rahulpardeshi84** [nisargjhaveri/WirelessAndroidAutoDongle#152]
Hi Nisarg,

Thanks for this great tool.
I was able to successfully connect and start Android Auto wirelessly on my Tata Nexon with OEM Head Unit via Raspberry Pi 0w.
However, I am facing one issue - When I connect to the wireless network named 'AAWirelessDongle', the mobile data connection in my phone gets disconnected and I am unable to use online live Maps for navigation and other internet dependent apps.
Is there any solution to this issue?
My phone is Samsung Galaxy M20, Android version 10.

Thanks
Rahul Pardeshi.

**Comment by nisargjhaveri** [comment]
> However, I am facing one issue - When I connect to the wireless network named 'AAWirelessDongle'... 

Are you connecting to the Wifi network manually from phone? You shouldn't need to do that. Once connected via Bluetooth, the Wifi network will automatically be connected. And at this point, you should also be able to use data. Manually connecting Wifi network forces phone to use it for internet as well, which won't work.

**Comment by nisargjhaveri** [comment]
I hope you were able to make it work by not connecting to the Wifi manually. Closing the issue for now. Feel free to reopen if this is still an issue.
