### ISSUE TITLE
Support fo Raspberry Pi 3 B/B+ 

### ISSUE THREAD

**Issue by anandmr1** [nisargjhaveri/WirelessAndroidAutoDongle#157]
Hi Nisarg, I own a Pi 3 B and would like to try this out. 

In the description it is mentioned "(Raspberry Pi 3 B+ is not supported), is there a limitation in Pi 3 B or B+ models due to which they cannot be supported.

**Comment by nisargjhaveri** [comment]
Raspberry Pi 3 B and B+ does not have support for USB OTG, it cannot function as a USB device/gadget, which is required for this to work.
