### ISSUE TITLE
pi zero 2 turning off repeateadly

### ISSUE THREAD

**Issue by vishnu3095** [nisargjhaveri/WirelessAndroidAutoDongle#167]
When i connect my pi zero 2 to headunit the bluetooth gets connected and immidiately turns off, and will turn on again. i have connected using micro usb port for data. but when i add a second cable to the power port the device stays on and works perfect. Is there any work around other than using 2 cables.

**Comment by nisargjhaveri** [comment]
Duplicate #88. More information is present in that issue. Let's continue the discussion there?
