### ISSUE TITLE
Works on 208 ii but car keep spamming BT request eventually leading to a disconnect to AADongle

### ISSUE THREAD

**Issue by LorisTecnology** [nisargjhaveri/WirelessAndroidAutoDongle#170]
So i've tested this with a Rpi 4 and works flawlessly however after a while the car start spamming for BT connection and my device disconnect from AADongle

Redmi note 10 pro with PixelOS

**Comment by nisargjhaveri** [comment]
> So i've tested this with a Rpi 4 and works flawlessly however after a while the car start spamming for BT connection and my device disconnect from AADongle

Can you elaborate more on this? The car BT should already be connected when Android Auto is connected. Is that not the case?

**Comment by LorisTecnology** [comment]
when i connect to the AADongle the device then connects to Peugout BT instead

**Comment by nisargjhaveri** [comment]
When the Android Auto connects, it is normal behaviour that the "AA Wireless Dongle" bluetooth will disconnect and the Car's bluetooth will connect automatically.

**Comment by LorisTecnology** [comment]
Using it for week now and everything works flawlessly. Thanks a lot

**Comment by nisargjhaveri** [comment]
Glad that it works well for you now. I'll close the issue for now.
