### ISSUE TITLE
4.1 on Pi Zero 2 has no Bluetooth to connect to for initial set up

### ISSUE THREAD

**Issue by ShaggyStallion** [nisargjhaveri/WirelessAndroidAutoDongle#174]
Title says it all... There's no Bluetooth to connect to for set up with 4.1 on a pi Zero 2

**Comment by nisargjhaveri** [comment]
If no bluetooth or wifi is created, I'd suggest verifying the following:
- Make sure the correct image is used for the board you're using.
- Make sure that the image was correctly written to the SD card and the Pi boots. You should see flickers in the LED on your board.
- Make data cable is good quality and the power supplied by the car is enough.

**Comment by ShaggyStallion** [comment]
Yes I have verified all of the steps mentioned. It was working with 4.0, although it developed a loop of crashing at times. I have not changed the cable and I verified that I am using the image for the zero 2 not the zero.

**Comment by ShaggyStallion** [comment]
Solved!! I had to delete the saved Bluetooth connection for the device that was on my phone from when it was running the previous version of the software. Once I deleted it and tried booting it up, the Bluetooth connection showed up!
