### ISSUE TITLE
Difficult Connection

### ISSUE THREAD

**Issue by aytacortac** [nisargjhaveri/WirelessAndroidAutoDongle#20]
My car is Toyota Corolla 2023 (European version, only wired Android Auto). My phone is Samsung Galaxy S20 FE.

I can barely connect to the Raspberry Pi. It rarely connects the first time. I need to try a second or third time. I have to restart the multimedia unit many times. Only then can it establish a connection. It does not disconnect once connected.

What can be done to connect it at once?

**Comment by nisargjhaveri** [comment]
From what you explained, very likely the head unit is timing out before we finally connect everything.

You can try this suggestion here: https://github.com/nisargjhaveri/AAWirelessDongle/issues/2#issuecomment-1783434263

If that doesn't work, we can try to do a handshake early without waiting for everything to connect.

**Comment by nisargjhaveri** [comment]
You can also check if the builds from #25 helps with more reliable connection in your case?

**Comment by nisargjhaveri** [comment]
You can also try out #35, should help with the timeouts.

**Comment by nisargjhaveri** [comment]
There have been multiple changes and I believe this issue should be fixed in latest builds. Closing this for now.
