### ISSUE TITLE
Issue in connecting with XL6 - 2022 Model

### ISSUE THREAD

**Issue by mrcheruvat** [nisargjhaveri/WirelessAndroidAutoDongle#214]
Hi, 
I bought Raspberry pi zero2 board and used a 32GB (FAT32) memory card. Flashing the image was successfull. I then tried connecting with XL6 inbuild infotainment system. Bluetooth first connects. then Wifi also gets connected for a fraction of second. phone notification shows android auto connected. then bluetooth gets disconnected and then notifcaton panel on phone starts showing searching android auto. The infotainment on car never show android auto connected ie withing the short time it is getting disconnected I think. This connection and disconnection happens continously. My phone is S24. I am using USB (DP DM) port to connect with car system. I have even tried with giving additoinal power to PWR IN port through car charging port connection. nothing worked...has anyone faced similiar issue? Is there any solution for this?

**Comment by akohli-86** [comment]
what was your solution for this?
