### ISSUE TITLE
Support for Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by pulkittt123** [nisargjhaveri/WirelessAndroidAutoDongle#229]
Hi Nisarg,

This is beautiful. I tried this on Raspberry Pi 3 Model B but it didnt work. And your notes also mention the same. Are you planning to make it work for Raspberry Pi 3 Model B?

**Comment by nisargjhaveri** [comment]
Raspberry Pi 3 Model B does not have OTG enabled USB port, which is required for the RPi to run in USB device mode.
