### ISSUE TITLE
Release binary images

### ISSUE THREAD

**Issue by GreenZeeGuy** [nisargjhaveri/WirelessAndroidAutoDongle#52]
Hello AAWirelessDongle team,

It looks like no new images have been released since Nov 2023 even though many issues have been fixed and checked in.
It will be great to have an updated set of binaries to try out !

Thanks in advance !

**Comment by nisargjhaveri** [comment]
Thanks for reminding. I was waiting for some of the changes to stabilize before creating a release, but will do this soon.

In the meantime you can use the generated builds from one of the recent CI runs on main branch.
https://github.com/nisargjhaveri/AAWirelessDongle/actions?query=branch%3Amain

**Comment by nisargjhaveri** [comment]
A new release has been created: https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/releases/tag/v0.3.0
