### ISSUE TITLE
Raspberry Pi compatible 

### ISSUE THREAD

**Issue by andrescabana86** [nisargjhaveri/WirelessAndroidAutoDongle#60]
Hello community

I've been looking into the repo and I could not find the list of compatible raspberry. Is the last version necessary? Can I buy a cheaper raspberry or any other compatible board?

**Comment by nisargjhaveri** [comment]
Currently Raspberry Pi Zero W, Zero 2 W, 3A, and 4 are supported. You can easily generate or download the builds for these.

**Comment by txikitin** [comment]
And 3B+?

**Comment by hkfuertes** [comment]
In fact, you don't use the micro USB, you need to use the USB A (on the 3A)...
