### ISSUE TITLE
Issue connecting phone to Rasberry pi W0 

### ISSUE THREAD

**Issue by chanakyaraichur** [nisargjhaveri/WirelessAndroidAutoDongle#64]
Hi,

 I have tried stable build 0.20 and latest build on Rasberry pi W0 but it's not working .
Android phone shows AAWireless in list but after connecting to it nothing happens . 
Even car head unit as well don't display info when connected to android auto port .

I am using Hyundai venue 2023 model . 

Have you came through this issue before ?
Is there any way to over come this problem ?

Can you provide video with steps so that we can also follow the same steps or check what mistake we are doing ?

Thanks and Regards,
Chanakya

**Comment by milindsoni** [comment]
Experiencing a similar problem with the Hyundai Venue 2023 model. When attempting to use wireless Android Auto, it successfully shows the Bluetooth connection, but after establishing the connection, nothing happens.

**Comment by nisargjhaveri** [comment]
This can sometimes happen if the car does not actually start AA in time even after usb is enabled from the dongle. If possible, please include the logs to know more.

**Comment by nisargjhaveri** [comment]
You can also try out the v0.4.0 which has some changes which might help in this case.

**Comment by nisargjhaveri** [comment]
We've been seeing a common issue with bad usb cables. I believe using a good data cable would solve this issue. Closing for now, feel free to reopen as needed.
