### ISSUE TITLE
2021 Kia Sorento, Raspberry Pi 3B+, One Plus 7T stuck at searching for Android Auto

### ISSUE THREAD

**Issue by sureiguess** [nisargjhaveri/WirelessAndroidAutoDongle#74]
The title pretty much describes it. I can connect bluetooth between my phone and the pi but that is where it stops. The image is where it stops. I have attached the logs, any help would be appreciated! Thanks
[Kia_hostapd_log.txt](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/files/14471799/Kia_hostapd_log.txt)
[Kia_message_Log.txt](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/files/14471801/Kia_message_Log.txt)

![IMG_20240302_121228](https://github.com/nisargjhaveri/WirelessAndroidAutoDongle/assets/33238639/b2b8bb22-ba9d-42f5-95e1-54ebd689630f)

**Comment by nisargjhaveri** [comment]
Raspberry Pi 3B+ is not supported, it does not have USB OTG capability.

**Comment by sureiguess** [comment]
My bad, thank you. I will try a different model.
