### ISSUE TITLE
Unable to connect Raspberry Pi 4 to aftermarket Stereo on Kia Rio 2018

### ISSUE THREAD

**Issue by HiroHP** [nisargjhaveri/WirelessAndroidAutoDongle#75]
I had Changed the headunit from my car into a BOSS BCPA10 headunit. Already tried to at least find the device in the Bluetooth app. But it still is not showing anything.
Would be really appreciated if some extra guidance was provided.

Not sure what is causing the real problem yet.

**Comment by mv92git** [comment]
+1
Car : Tata altroz
Phone : s23 ultra
Ver : 0.3

**Comment by mariolugo2** [comment]
> +1 Coche: Tata altroz​​Teléfono: s23 ultra Ver: 0.3 Pi0w
> 
> 0.3 no muestra Bluetooth en la configuración. 0.2 tiene muchos errores y muestra que busca AA la mayor parte del tiempo.
> 
> ¿Me ayudará a construir mi propia imagen? No estoy seguro si eso marca la diferencia.

test mi img , only test this give my name bt profile

https://www.mediafire.com/file/23qqxqdptdkvui4/sdcard2-gta.img/file

**Comment by mariolugo2** [comment]
> +1 Coche: Tata altroz​​Teléfono: s23 ultra Ver: 0.3 Pi0w
> 
> 0.3 no muestra Bluetooth en la configuración. 0.2 tiene muchos errores y muestra que busca AA la mayor parte del tiempo.
> 
> ¿Me ayudará a construir mi propia imagen? No estoy seguro si eso marca la diferencia.

test this image 
https://www.mediafire.com/file/h6syv4ihyhrpi8w/sdcard.img/file

**Comment by nisargjhaveri** [comment]
@mariolugo2 let's not share local images here. If you have some local changes, please share the changes with a PR?

**Comment by mv92git** [comment]
Tried 0.3.1 seeing new release, Bluetooth now is shown persistently in Bluetooth settings, though Android auto connects for a brief moment and then disconnects. Will try sharing logs later.

**Comment by nisargjhaveri** [comment]
Please try out version 0.4.0 if it helps. And share the logs if possible if you're still facing issues.

**Comment by nisargjhaveri** [comment]
Closing for now as there are no updates in a while. I hope things got better with newer version?
