### ISSUE TITLE
Raspberry Pi 3 Model B

### ISSUE THREAD

**Issue by kenjori** [nisargjhaveri/WirelessAndroidAutoDongle#76]
Hello,

Is AAWirelessDongle compatible with Raspberry Pi 3 Model B? 

I tried with [raspberrypi3a-sdcard.img.xz]. Pi boots and my phone connects AAWirelessDongle via bluetooth. Pi is connected to the car via usb but my car (Peugeot 3008) does not recognize AA.

**Comment by nisargjhaveri** [comment]
Raspberry Pi 3 Model B is not compatible as it does not have USB otg support.
