### ISSUE TITLE
Raspberry PI 3 B+ issue 

### ISSUE THREAD

**Issue by akalhan** [nisargjhaveri/WirelessAndroidAutoDongle#93]
PI 3 B+ doesn't have any OTG mode but only USB Host Mode. Hence not connecting to the Car AA - Any options?

**Comment by nisargjhaveri** [comment]
Only Raspberry Pi 3 model A is support not B+. B+ doesn't have OTG mode as you mentioned, not much we can do without it.

**Comment by akalhan** [comment]
> Only Raspberry Pi 3 model A is support not B+. B+ doesn't have OTG mode as you mentioned, not much we can do without it.

thank you
