### ISSUE TITLE
Question: Multiple users

### ISSUE THREAD

**Issue by Phill78** [nisargjhaveri/WirelessAndroidAutoDongle#96]
This thing sounds awesome. I have questions re multiple users:

1) does it support more than one user?
2) if so, how do you toggle between users?

Thanks
Phill

**Comment by nisargjhaveri** [comment]
You can pair multiple devices with the Rpi. With the latest version 0.4.0, in dongle mode, it should connect to the device that is also connected to the headunit via Bluetooth. In older modes, it would always connect to the first available device. If more than one devices are available, you need to ensure only one has bleuetooth on to reliably connect to that device.

**Comment by Phill78** [comment]
Thank you, that is really helpful
